import type { SuggestionGroup } from './suggestions';

// Tags for a card's role in a deck, not trivia. Each group leads with its broadest tag, which also matches its children.
const TAGS: Record<string, Record<string, string>> = {
  Removal: {
    removal: 'Any way of getting rid of opposing permanents',
    'spot-removal': 'Removes a single target permanent',
    sweeper: 'Removes many permanents at once (board wipe)',
    'sweeper-one-sided': 'Board wipe that hits only your opponents',
    'removal-creature': 'Removes a creature',
    'removal-artifact': 'Removes an artifact',
    'removal-enchantment': 'Removes an enchantment',
    'removal-planeswalker': 'Removes a planeswalker',
    'removal-land': 'Removes a land',
    'removal-destroy': 'Removes by destroying',
    'removal-exile': 'Removes by exiling',
    'removal-bounce': "Removes by returning to its owner's hand",
    'removal-sacrifice': 'Makes a player sacrifice (edict)',
    'removal-toughness': 'Kills by lowering toughness (-X/-X)',
    'removal-tuck': 'Removes by putting into the library',
    'removal-fight': 'Removes by making creatures fight',
    'one-sided-fight': 'Your creature deals damage without taking any back',
    'disenchant-naturalize': 'Destroys an artifact or enchantment',
    pacifism: 'Aura that stops a creature from attacking or blocking',
    burn: 'Deals direct damage',
    'burn-creature': 'Deals damage to a creature',
    'burn-player': 'Deals damage to a player',
    'burn-any': 'Deals damage to any target',
    pinger: 'Repeatedly deals small amounts of damage',
  },
  Interaction: {
    counterspell: 'Counters a spell',
    'counterspell-soft': 'Counters unless its controller pays a cost',
    'counterspell-ability': 'Counters an activated or triggered ability',
    discard: 'Makes a player discard cards',
    thoughtseize: 'Look at a hand and choose the card to discard',
    'hand-disruption': "Messes with an opponent's hand",
    'tapper-creature': 'Taps a creature',
    'lockdown-creature': 'Keeps a creature tapped or unable to act',
    fog: 'Prevents all combat damage this turn',
    'pseudo-fog': 'Stops a combat in some other way than prevention',
    'hate-graveyard': 'Graveyard hate: exiles or shuts off graveyards',
    'theft-creature': 'Gains control of a creature',
    threaten: 'Steals a creature until end of turn',
    hatebear: 'Cheap creature with a restrictive (stax) effect',
    'cost-increaser': 'Makes spells or abilities cost more',
    silence: 'Stops opponents from casting spells this turn',
    'mass-land-denial': 'Destroys or locks down lands en masse',
    pillowfort: 'Discourages opponents from attacking you',
  },
  'Card advantage': {
    draw: 'Draws cards',
    'card-advantage': 'Nets you more cards than it costs',
    cantrip: 'Replaces itself by drawing a card',
    'draw-engine': 'Draws cards repeatedly over time',
    'pure-draw': 'Draws cards with no other strings attached',
    'burst-draw': 'Draws several cards at once',
    loot: 'Draw, then discard',
    rummage: 'Discard, then draw',
    wheel: 'Discard hands and draw new ones',
    impulse: 'Look at the top cards and take one',
    'impulsive-draw': 'Exile top cards; you may play them for a while',
    'repeatable-impulsive-draw': 'Impulsive draw you can repeat',
    scry: 'Scry: look at top cards, keep or bottom them',
    surveil: 'Surveil: look at top cards, keep or mill them',
    curiosity: 'Draws a card when it deals damage',
  },
  Tutors: {
    tutor: 'Searches your library for a card',
    'tutor-to-hand': 'Puts the found card into your hand',
    'tutor-to-battlefield': 'Puts the found card onto the battlefield',
    'tutor-creature': 'Searches for a creature',
    'tutor-land': 'Searches for a land',
    'tutor-land-basic': 'Searches for a basic land',
    'tutor-artifact': 'Searches for an artifact',
    'tutor-enchantment': 'Searches for an enchantment',
    'tutor-instant': 'Searches for an instant',
    'tutor-sorcery': 'Searches for a sorcery',
    wish: 'Gets a card from outside the game',
  },
  Mana: {
    ramp: 'Speeds up your mana',
    'land-ramp': 'Puts extra lands onto the battlefield',
    'mana-rock': 'Artifact that taps for mana',
    'mana-dork': 'Creature that taps for mana',
    ritual: 'One-shot spell that adds mana',
    'cost-reducer': 'Makes your spells cheaper',
    'adds-multiple-mana': 'Adds two or more mana at once',
    'mana-increaser': 'Makes your mana sources produce more',
    'mana-filter': 'Turns mana into other colors',
    'mana-sink': 'Lets you spend spare mana',
    'extra-land': 'Lets you play more lands per turn',
    'play-additional-land': 'Play an additional land this turn',
    'repeatable-treasures': 'Makes Treasure tokens over and over',
  },
  Lands: {
    'utility-land': 'Land with a useful ability beyond mana',
    'dual-land': 'Land that taps for two colors',
    fetchland: 'Sacrifices itself to fetch a land',
    shockland: 'Dual land; pay 2 life or it enters tapped',
    painland: 'Colored mana costs you 1 damage',
    triome: 'Tri-color land with basic types and cycling',
    tapland: 'Land that always enters tapped',
    bounceland: 'Returns a land to hand; taps for two mana',
    filterland: 'Filters mana into two colors',
    gainland: 'Enters tapped and gains you 1 life',
    creatureland: 'Land that can become a creature',
    'storage-land': 'Stores mana as counters for later',
    'rainbow-land': 'Taps for mana of any color',
    'sol-land': 'Land that taps for two or more mana',
  },
  Graveyard: {
    recursion: 'Brings cards back from the graveyard',
    reanimate: 'Returns something from a graveyard to play',
    'reanimate-creature': 'Returns a creature from a graveyard to play',
    'reanimate-self': 'Can return itself from the graveyard to play',
    'mass-reanimation': 'Returns many cards from graveyards to play',
    regrowth: 'Returns a card from the graveyard to hand',
    'regrowth-creature': 'Returns a creature card to hand',
    'regrowth-instant': 'Returns an instant card to hand',
    'regrowth-sorcery': 'Returns a sorcery card to hand',
    'castable-from-graveyard': 'Can be cast from the graveyard',
    mill: 'Puts cards from a library into the graveyard',
    'mill-self': 'Mills your own library',
    'mill-opponent': "Mills an opponent's library",
    'graveyard-fuel': 'Uses cards in the graveyard as a resource',
    'cards-in-graveyard-matter': 'Better with more cards in the graveyard',
  },
  Sacrifice: {
    'sacrifice-outlet': 'Lets you sacrifice permanents',
    'sacrifice-outlet-creature': 'Lets you sacrifice creatures',
    'free-sacrifice-outlet': 'Sacrifice outlet that costs no mana',
    'your-sacrifice-matters': 'Rewards you for sacrificing',
    'death-trigger': 'Triggers when a creature dies',
    'blood-artist-ability': 'Drains life whenever a creature dies',
    'grave-pact': 'Opponents sacrifice when your creatures die',
    'discard-outlet': 'Lets you discard cards at will',
  },
  'Creatures & combat': {
    evasion: 'Hard to block',
    unblockable: "Can't be blocked",
    anthem: 'Pumps your whole team',
    'keyword-anthem': 'Gives your whole team a keyword',
    overrun: 'Big one-turn team pump, often with trample',
    'combat-trick': 'Instant-speed trick to win a combat',
    'giant-growth': 'Instant pump for a single creature',
    protection: 'Protects your permanents',
    'protects-creature': 'Keeps a creature from being removed',
    'gives-haste': 'Gives creatures haste',
    'gives-flying': 'Gives creatures flying',
    'gives-trample': 'Gives creatures trample',
    'gives-double-strike': 'Gives creatures double strike',
    'gives-indestructible': 'Gives indestructible',
    'gives-hexproof': 'Gives hexproof',
    'attack-trigger': 'Triggers when it attacks',
    'attacking-matters': 'Rewards attacking',
    'extra-combat-phase': 'Gives an extra combat phase',
    'force-attacker': 'Forces creatures to attack',
    lure: 'Forces creatures to block it',
    'power-doubler': "Doubles a creature's power",
  },
  'Tokens, counters & copies': {
    'repeatable-creature-tokens': 'Makes creature tokens over and over',
    'token-doubler': 'Doubles the tokens you make',
    'synergy-token': 'Benefits from having creature tokens',
    'gives-pp-counters': 'Puts +1/+1 counters on creatures',
    'pp-counters-matter': 'Rewards +1/+1 counters',
    'counter-doubler': 'Doubles counters put on things',
    'pseudo-proliferate': 'Adds more of the counters already there',
    'repeatable-proliferate': 'Proliferates over and over',
    'move-counters': 'Moves counters between permanents',
    'copy-creature': 'Copies a creature',
    clone: 'Enters as a copy of a creature',
    'copy-spell': 'Copies a spell',
    flicker: 'Exiles and returns a permanent (blink)',
    'flicker-creature': 'Blinks a creature to reuse its ETB',
  },
  Life: {
    lifegain: 'Gains you life',
    'repeatable-lifegain': 'Gains you life over and over',
    'lifegain-matters': 'Rewards gaining life',
    'soul-warden-ability': 'Gains 1 life whenever a creature enters',
    pridemate: 'Grows whenever you gain life',
    'drain-life': 'Opponent loses life and you gain it',
    'opponent-loses-life': 'Makes opponents lose life',
    'group-slug': 'Damages every player, you included',
    'life-payment': 'Costs life to cast or activate',
    'lifegain-to-damage': 'Turns life gained into damage',
  },
  'Themes & synergies': {
    typal: 'Rewards a creature type (tribal)',
    landfall: 'Triggers when a land enters under your control',
    'lands-matter': 'Rewards lands in play or played',
    'synergy-artifact': 'Better with artifacts',
    'synergy-enchantment': 'Better with enchantments',
    'synergy-equipment': 'Better with Equipment (Voltron)',
    'synergy-aura': 'Better with Auras (Voltron)',
    'synergy-vehicle': 'Better with Vehicles',
    'synergy-instant': 'Better with instants (spellslinger)',
    'synergy-sorcery': 'Better with sorceries (spellslinger)',
    'cast-trigger-you': 'Triggers when you cast a spell',
    magecraft: 'Triggers when you cast or copy instant/sorcery',
    'synergy-legendary': 'Better with legendary permanents',
    'synergy-commander': 'Better with your commander',
    'synergy-mill': 'Better when cards are milled',
    'group-hug': 'Helps every player at the table',
    'theft-cast': 'Casts cards opponents own',
    'extra-turn': 'Gives an extra turn',
    'alternate-win-condition': 'Wins the game in a different way',
  },
};

export const TAG_DESCRIPTIONS: ReadonlyMap<string, string> = new Map(
  Object.values(TAGS).flatMap((tags) => Object.entries(tags)),
);

export const TAG_GROUPS: readonly SuggestionGroup[] = Object.entries(TAGS).map(([label, tags]) => ({
  label,
  items: Object.keys(tags),
}));
